### ISSUE TITLE
Question about the img_size？

### ISSUE THREAD

**Issue by yannqi** [vvvb-github/AVSegFormer#3]
I found your paper said that your img_size is 224x224, however, in your code,  the img_size is 512, which one is right？[https://github.com/vvvb-github/AVSegFormer/blob/master/dataloader/s4_dataset.py](https://github.com/vvvb-github/AVSegFormer/blob/master/dataloader/s4_dataset.py)

**Comment by CleyLyChen** [comment]
hi, @yannqi, the author note the img_size=512 as AVSegFormer-PVTv2* in their AAAI 2024 paper, Here is the table:
![image](https://github.com/vvvb-github/AVSegFormer/assets/96591070/b0a515c5-404e-4ea0-ad39-55a6b036fab9)

**Comment by CleyLyChen** [comment]
hi, @yannqi, the author note the img_size=512 as AVSegFormer-PVTv2* in their AAAI 2024 paper, Here is the table:
![image](https://github.com/vvvb-github/AVSegFormer/assets/96591070/b0a515c5-404e-4ea0-ad39-55a6b036fab9)

**Comment by yannqi** [comment]
I noticed the change of the arixv. Thanks for your reply!
